services:
  tornocapp:
    image: ghcr.io/blacksmithop/toa/torn-proxy:main
    container_name: tornocapp
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    external: true