version: '3.8'

services:
  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    networks:
      - cf

  # Nginx Proxy Manager (NPM)
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    networks:
      - cf
      - services
    volumes:
      - ./homelab/data/npm:/data
      - ./homelab/data/letsencrypt:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"
    # Ports are commented out as NPM will be accessed via Cloudflare Tunnel
    # ports:
    #   - "80:80"
    #   - "81:81"
    #   - "443:443"

  # Portainer
  portainer:
    image: portainer/portainer-ce:latest
    # ports:
    #   - 9443:9443
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - services

  # Plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    # ports:
    #   - 32400:32400/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./homelab/media/library:/config
      - ./homelab/media/series:/tv
      - ./homelab/media/movies:/movies
    restart: unless-stopped
    networks:
      - services

  # Ollama
  ollama:
    image: ollama/ollama:latest
    # ports:
    #   - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    network_mode: host
    networks:
      - services

volumes:
  portainer-data:

networks:
  cf:
    name: cf
  services:
    name: services