services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    networks:
      - services
    restart: unless-stopped
    init: true
networks:
  services:
    external: true