services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    # ports:
    #   - "5000:80"
    networks:
      - services
    restart: unless-stopped
    init: true
networks:
  services:
    external: true