services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - services
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - jellyfin-media:/media
    restart: unless-stopped 
    ports:
    - 8096:8096

volumes:
  jellyfin-config:
    name: jellyfin-config
  jellyfin-cache:
    name: jellyfin-cache
  jellyfin-media:
    name: jellyfin-media

networks:
  services:
    external: true