services:
  api:
    image: ghcr.io/blacksmithop/blacksmithop/backend:main
    container_name: api
    restart: unless-stopped
    networks:
      - services
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
networks:
  services:
    external: true