services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock # For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev, homelab.abhinavkm.com
    networks:
      - services

networks:
  services:
    external: true